### ISSUE TITLE
Deployment just doesn't work, bucket error, and it seems some more issues

### ISSUE THREAD

**Issue by arielbeckjit** [awslabs/sandbox-accounts-for-events#31]
We have several issues i want to (maybe submit a PR) and to see that they are really issues:

Related to bucket configuration:
https://github.com/awslabs/sandbox-accounts-for-events/blob/main/install/sandbox-accounts-for-events-install.yaml#L65

Relates to this: https://github.com/aws/aws-cdk/issues/25288

i've updated the buckets to:
```
  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DceTerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        !Sub
          - 'dce-terraform-state-${RandomGUID}'
          - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: dce-terraform-logs
```

and it works.

For the 2nd issue i'm facing - is that there's a terraform output command for namespace and artifacts_bucket_name:
https://github.com/awslabs/sandbox-accounts-for-events/blob/35d886c71b2bf4b3db067da5caf00be7f49d702b/dce-integration/Makefile#L41

Those are outputs that i don't find anywhere in the project (of the terraform modules), and then i fail to deploy with)
```
Invalid bucket name "[33m│[0m": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3\|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$\|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
Because those values are empty. I also don't see any reference for those values in the rather small terraform modules.
```

Is this project even maintained?
