### ISSUE TITLE
Depreecated lambda runtime, failed deployment

### ISSUE THREAD

**Issue by Onolisk** [awslabs/sandbox-accounts-for-events#51]
Hi team. 

Python 3.7 was recently deprecated as a Lambda runtim and can no longer be deployed or updated. This runtime is currently in use under install/sandbox-accounts-for-events-install.yaml. Please update the code to a supported runtime.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by moellr** [comment]
Confirmed.
Similar issue occurs with nodejs14.x Lambda functions created by Amplify CLI (e.g. "UpdateRolesWithIDPFunction).
A fix for this project is currently in progress...

**Comment by BrutalSimplicity** [comment]
I needed to fix this recently, and it looks like there are only two small changes that need to be made to the `amplify.yml`

1. Update the amplify cli to v11+. NodeJS build deployment runtimes were updated to v18 in this version.
2. Update values in parameter store with JSON-encoded string values. The Amplify CLI appears to assume these values will be strings by default. My guess is that it doesn't expect the SSM parameter to be created or modified outside of Amplify. As example, this: `\"${DCE_API_GW}\"`, changes to: `\"\\\"${DCE_API_GW}\\\"\"`

```yaml
      commands:
        # ...
        - npm i -g @aws-amplify/cli@11  # <--- Update to v11 here
    build:
      commands:
        # ...
        # update Amplify parameter files to connect Amplify frontend with backend
        - aws ssm put-parameter --cli-input-json "{\"Type\":\"String\",\"Name\":\"/amplify/${AWS_APP_ID}/${CI_BRANCH}/AMPLIFY_function_safeLoginApi_dceApiGw\",\"Value\":\"\\\"${DCE_API_GW}\\\"\",\"Overwrite\":true}"
        - aws ssm put-parameter --cli-input-json "{\"Type\":\"String\",\"Name\":\"/amplify/${AWS_APP_ID}/${CI_BRANCH}/AMPLIFY_function_safeOperatorApi_dceApiGw\",\"Value\":\"\\\"${DCE_API_GW}\\\"\",\"Overwrite\":true}"
        - aws ssm put-parameter --cli-input-json "{\"Type\":\"String\",\"Name\":\"/amplify/${AWS_APP_ID}/${CI_BRANCH}/AMPLIFY_function_safeAdminApi_dceApiGw\",\"Value\":\"\\\"${DCE_API_GW}\\\"\",\"Overwrite\":true}"
        - aws ssm put-parameter --cli-input-json "{\"Type\":\"String\",\"Name\":\"/amplify/${AWS_APP_ID}/${CI_BRANCH}/AMPLIFY_function_safeOperatorApi_dceLeasesTable\",\"Value\":\"\\\"${DCE_LEASES_TABLE}\\\"\",\"Overwrite\":true}"
        - aws ssm put-parameter --cli-input-json "{\"Type\":\"String\",\"Name\":\"/amplify/${AWS_APP_ID}/${CI_BRANCH}/AMPLIFY_function_safeAdminApi_dceAccountsTable\",\"Value\":\"\\\"${DCE_ACCOUNTS_TABLE}\\\"\",\"Overwrite\":true}"
       # ...
```
